/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BunnyNotesInterface extends ethers.utils.Interface {
  functions: {
    "_owner()": FunctionFragment;
    "calculateFee(uint256)": FunctionFragment;
    "commitments(bytes32)": FunctionFragment;
    "depositEth(bytes32,uint256)": FunctionFragment;
    "depositToken(bytes32,uint256,address)": FunctionFragment;
    "feeDivider()": FunctionFragment;
    "feelessToken()": FunctionFragment;
    "isSpent(bytes32)": FunctionFragment;
    "isSpentArray(bytes32[])": FunctionFragment;
    "nullifierHashes(bytes32)": FunctionFragment;
    "setFeelessToken(address)": FunctionFragment;
    "verifier()": FunctionFragment;
    "withdraw(uint256[8],bytes32,bytes32,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "_owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEth",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeDivider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feelessToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isSpent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isSpentArray",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeelessToken",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      BytesLike,
      BytesLike,
      string
    ]
  ): string;

  decodeFunctionResult(functionFragment: "_owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositEth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeDivider", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feelessToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSpent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSpentArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifierHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeelessToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "DepositETH(bytes32,address,uint256,uint256,uint256)": EventFragment;
    "DepositToken(bytes32,address,uint256,uint256,uint256,address)": EventFragment;
    "WithdrawBunnyNote(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositETH"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawBunnyNote"): EventFragment;
}

export type DepositETHEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber] & {
    commitment: string;
    depositFor: string;
    timestamp: BigNumber;
    denomination: BigNumber;
    fee: BigNumber;
  }
>;

export type DepositTokenEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string] & {
    commitment: string;
    depositFor: string;
    timestamp: BigNumber;
    amount: BigNumber;
    fee: BigNumber;
    token: string;
  }
>;

export type WithdrawBunnyNoteEvent = TypedEvent<
  [string, string, string] & { from: string; to: string; commitment: string }
>;

export class BunnyNotes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BunnyNotesInterface;

  functions: {
    _owner(overrides?: CallOverrides): Promise<[string]>;

    calculateFee(
      denomination: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    commitments(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        string,
        string,
        BigNumber,
        BigNumber,
        boolean,
        string,
        BigNumber
      ] & {
        used: boolean;
        creator: string;
        recipient: string;
        createdDate: BigNumber;
        spentDate: BigNumber;
        usesToken: boolean;
        token: string;
        denomination: BigNumber;
      }
    >;

    depositEth(
      _commitment: BytesLike,
      denomination: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositToken(
      _commitment: BytesLike,
      denomination: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    feeDivider(overrides?: CallOverrides): Promise<[BigNumber]>;

    feelessToken(overrides?: CallOverrides): Promise<[string]>;

    isSpent(
      _nullifierHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSpentArray(
      _nullifierHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean[]] & { spent: boolean[] }>;

    nullifierHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setFeelessToken(
      newFeelesstoken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifier(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      _proof: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      _nullifierHash: BytesLike,
      _commitment: BytesLike,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _owner(overrides?: CallOverrides): Promise<string>;

  calculateFee(
    denomination: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  commitments(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      string,
      string,
      BigNumber,
      BigNumber,
      boolean,
      string,
      BigNumber
    ] & {
      used: boolean;
      creator: string;
      recipient: string;
      createdDate: BigNumber;
      spentDate: BigNumber;
      usesToken: boolean;
      token: string;
      denomination: BigNumber;
    }
  >;

  depositEth(
    _commitment: BytesLike,
    denomination: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositToken(
    _commitment: BytesLike,
    denomination: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  feeDivider(overrides?: CallOverrides): Promise<BigNumber>;

  feelessToken(overrides?: CallOverrides): Promise<string>;

  isSpent(
    _nullifierHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSpentArray(
    _nullifierHashes: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean[]>;

  nullifierHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  setFeelessToken(
    newFeelesstoken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifier(overrides?: CallOverrides): Promise<string>;

  withdraw(
    _proof: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    _nullifierHash: BytesLike,
    _commitment: BytesLike,
    _recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _owner(overrides?: CallOverrides): Promise<string>;

    calculateFee(
      denomination: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commitments(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        string,
        string,
        BigNumber,
        BigNumber,
        boolean,
        string,
        BigNumber
      ] & {
        used: boolean;
        creator: string;
        recipient: string;
        createdDate: BigNumber;
        spentDate: BigNumber;
        usesToken: boolean;
        token: string;
        denomination: BigNumber;
      }
    >;

    depositEth(
      _commitment: BytesLike,
      denomination: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositToken(
      _commitment: BytesLike,
      denomination: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    feeDivider(overrides?: CallOverrides): Promise<BigNumber>;

    feelessToken(overrides?: CallOverrides): Promise<string>;

    isSpent(
      _nullifierHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSpentArray(
      _nullifierHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean[]>;

    nullifierHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setFeelessToken(
      newFeelesstoken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verifier(overrides?: CallOverrides): Promise<string>;

    withdraw(
      _proof: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      _nullifierHash: BytesLike,
      _commitment: BytesLike,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositETH(bytes32,address,uint256,uint256,uint256)"(
      commitment?: BytesLike | null,
      depositFor?: null,
      timestamp?: null,
      denomination?: null,
      fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        commitment: string;
        depositFor: string;
        timestamp: BigNumber;
        denomination: BigNumber;
        fee: BigNumber;
      }
    >;

    DepositETH(
      commitment?: BytesLike | null,
      depositFor?: null,
      timestamp?: null,
      denomination?: null,
      fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        commitment: string;
        depositFor: string;
        timestamp: BigNumber;
        denomination: BigNumber;
        fee: BigNumber;
      }
    >;

    "DepositToken(bytes32,address,uint256,uint256,uint256,address)"(
      commitment?: BytesLike | null,
      depositFor?: null,
      timestamp?: null,
      amount?: null,
      fee?: null,
      token?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, string],
      {
        commitment: string;
        depositFor: string;
        timestamp: BigNumber;
        amount: BigNumber;
        fee: BigNumber;
        token: string;
      }
    >;

    DepositToken(
      commitment?: BytesLike | null,
      depositFor?: null,
      timestamp?: null,
      amount?: null,
      fee?: null,
      token?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, string],
      {
        commitment: string;
        depositFor: string;
        timestamp: BigNumber;
        amount: BigNumber;
        fee: BigNumber;
        token: string;
      }
    >;

    "WithdrawBunnyNote(address,address,bytes32)"(
      from?: null,
      to?: null,
      commitment?: null
    ): TypedEventFilter<
      [string, string, string],
      { from: string; to: string; commitment: string }
    >;

    WithdrawBunnyNote(
      from?: null,
      to?: null,
      commitment?: null
    ): TypedEventFilter<
      [string, string, string],
      { from: string; to: string; commitment: string }
    >;
  };

  estimateGas: {
    _owner(overrides?: CallOverrides): Promise<BigNumber>;

    calculateFee(
      denomination: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commitments(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    depositEth(
      _commitment: BytesLike,
      denomination: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositToken(
      _commitment: BytesLike,
      denomination: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    feeDivider(overrides?: CallOverrides): Promise<BigNumber>;

    feelessToken(overrides?: CallOverrides): Promise<BigNumber>;

    isSpent(
      _nullifierHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSpentArray(
      _nullifierHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nullifierHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFeelessToken(
      newFeelesstoken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifier(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _proof: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      _nullifierHash: BytesLike,
      _commitment: BytesLike,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateFee(
      denomination: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    commitments(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositEth(
      _commitment: BytesLike,
      denomination: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositToken(
      _commitment: BytesLike,
      denomination: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    feeDivider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feelessToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSpent(
      _nullifierHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSpentArray(
      _nullifierHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nullifierHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFeelessToken(
      newFeelesstoken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _proof: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      _nullifierHash: BytesLike,
      _commitment: BytesLike,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
